# Generated by Django 5.0.6 on 2024-05-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('marital', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('default', models.CharField(max_length=50)),
                ('housing', models.CharField(max_length=50)),
                ('loan', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('day_of_week', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('campaign', models.IntegerField()),
                ('pdays', models.IntegerField()),
                ('previous', models.IntegerField()),
                ('poutcome', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit_app.user')),
            ],
        ),
    ]
