# Generated by Django 5.0.6 on 2024-05-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
